version: '3'

services:
  app:
    build:
      context: ../
      dockerfile: ./deployment/Dockerfile
    entrypoint: ["./wait-for-it.sh", "postgres:5432", "--", "./comparty-bot"]
    restart: always
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    networks:
      - backend

  postgres:
    image: postgres:14-bullseye
    restart: always
    hostname: postgres
    env_file:
      - .env
    volumes:
      - "pg-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - backend
  redis:
    image: redis:bullseye
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:

volumes:
  pg-data: