version: '3'

services:
  app:
    build:
      context: ../
      dockerfile: ./deployment/Dockerfile
    entrypoint: ["./wait-for-it.sh", "postgres:5432", "--", "./comparty-bot"]
    restart: on-failure
    depends_on:
      - redis
      - postgres
    env_file:
      - example.env
    networks:
      - backend

  postgres:
    image: postgres:14-bullseye
    restart: on-failure
    hostname: postgres
    env_file:
      - example.env
    volumes:
      - $PWD/pg-data:/app/pg-data/
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:bullseye
    restart: unless-stopped
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
